"""Render player_guide_<code>.html for every language the game ships.

One template (this file plus style.py and render.py), one set of balance numbers
(numbers.py), one set of in-game proper names (names.py, generated by
extract_names.py) and one prose dictionary per language under lang/.

A balance fix is a single edit in numbers.py and a rebuild; a wording fix
touches exactly one language file.

Run:  python guide/build.py            # every language that has a lang/ file
      python guide/build.py tr de      # just those two
"""

import importlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import names as names_module
import render as render_module
import style as style_module

LANGUAGES = [
    "en", "tr", "de", "fr", "es", "es_la", "it", "pl", "pt_br", "ru", "uk",
    "ja", "ko", "zh_hans", "zh_hant", "th", "id", "vi",
]

_CACHE = {}

PAGE = """<!DOCTYPE html>
<html lang="{html_lang}">
<head>
<meta charset="utf-8">
<title>{title}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{description}">
<style>{css}</style>
</head>
<body>

<input type="checkbox" id="nav-toggle">

<div class="topbar">
  <span class="topbar-title">&#9935; {brand_sub}</span>
  <label class="nav-toggle-btn" for="nav-toggle">{contents}</label>
</div>

<div class="shell">
  <nav class="toc" aria-label="{contents}">
    <div class="toc-brand">{brand}<small>{brand_sub}</small></div>
    <ul class="toc-list">
      {toc}
    </ul>
  </nav>

  <main>
    <header class="hero">
      <div class="strata" role="presentation"></div>
      <div class="eyebrow">{eyebrow}</div>
      <h1 class="title">{headline}</h1>
      <p class="subtitle">{subtitle}</p>
      {langbar}
    </header>

    {sections}

    <footer class="doc-footer">{footer}</footer>
  </main>
</div>

</body>
</html>
"""

SECTION = """<section id="{id}">
      <div class="section-head"><span class="section-num">{number}</span><h2>{title}</h2></div>
      <p class="section-dek">{dek}</p>
      {blocks}
    </section>"""

LANGBAR = """<div class="langbar">
        <div class="langbar-label">{label}</div>
        <div class="langbar-list">{items}</div>
      </div>"""


def load_language(code):
    if code not in _CACHE:
        _CACHE[code] = importlib.import_module("lang." + code).LANG
    return _CACHE[code]


def available_languages():
    return [code for code in LANGUAGES if os.path.exists(os.path.join(HERE, "lang", code + ".py"))]


def language_bar(current, lang):
    items = []
    for code in available_languages():
        other = load_language(code)
        if code == current:
            items.append("<span>{0}</span>".format(other["name"]))
        else:
            items.append('<a href="player_guide_{0}.html" hreflang="{1}">{2}</a>'.format(
                code, other["html_lang"], other["name"]))
    return LANGBAR.format(label=lang["labels"]["language"], items="".join(items))


def render(code):
    lang = load_language(code)
    names = names_module.NAMES[code]
    values, locale, labels = render_module.build_tokens(lang, names)
    fill = render_module.fill

    toc = []
    sections = []
    for index, section in enumerate(lang["sections"], start=1):
        number = "{0:02d}".format(index)
        toc.append('<li><a href="#{0}"><span class="toc-num">{1}</span>{2}</a></li>'.format(
            section["id"], number, fill(section["title"], values)))
        blocks = "\n      ".join(
            render_module.render_block(block, lang, values, names, locale, labels)
            for block in section["blocks"]
        )
        sections.append(SECTION.format(
            id=section["id"],
            number=number,
            title=fill(section["title"], values),
            dek=fill(section["dek"], values),
            blocks=blocks,
        ))

    return PAGE.format(
        html_lang=lang["html_lang"],
        title=fill(lang["title"], values),
        description=fill(lang["description"], values),
        css=style_module.CSS,
        brand=lang["brand"],
        brand_sub=fill(lang["brand_sub"], values),
        contents=lang["labels"]["contents"],
        toc="\n      ".join(toc),
        eyebrow=fill(lang["eyebrow"], values),
        headline=fill(lang["headline"], values),
        subtitle=fill(lang["subtitle"], values),
        langbar=language_bar(code, lang),
        sections="\n\n    ".join(sections),
        footer=fill(lang["footer"], values),
    )


def main():
    requested = sys.argv[1:] or available_languages()
    for code in requested:
        path = os.path.join(ROOT, "player_guide_{0}.html".format(code))
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(render(code))
        print("wrote {0}".format(os.path.basename(path)))


if __name__ == "__main__":
    main()
